name: Deploy SPA to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write  # This ensures the workflow has write permissions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # specify your node version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Modify index.html paths
        run: |
          sed -i 's|<script type="module" crossorigin src="/assets/|<script type="module" crossorigin src="./assets/|' ./dist/index.html
          sed -i 's|<link rel="stylesheet" crossorigin href="/assets/|<link rel="stylesheet" crossorigin href="./assets/|' ./dist/index.html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ensure this matches your build output directory